"""
Templates for Jupyter Notebook Export

Contains the helper module template and notebook cell generation functions.
"""
from pathlib import Path
from typing import List, Dict, Optional, Tuple
import json


# ============================================================================
# HELPER MODULE TEMPLATE
# ============================================================================

HELPER_MODULE_TEMPLATE = '''"""
HD-sEMG Workfolder Analysis Helper

Auto-generated by hdsemg-pipe for Jupyter notebook analysis.
Provides easy access to folder paths, metadata, and pipeline summary.
"""
import json
from pathlib import Path
from typing import List, Dict, Optional, Tuple
import os


class WorkfolderPaths:
    """Easy access to all workfolder paths and files."""

    def __init__(self, workfolder: str):
        self.workfolder = Path(workfolder)
        self.original_files = self.workfolder / "original_files"
        self.associated_grids = self.workfolder / "associated_grids"
        self.line_noise_cleaned = self.workfolder / "line_noise_cleaned"
        self.cropped_signal = self.workfolder / "cropped_signal"
        self.channelselection = self.workfolder / "channelselection"
        self.decomposition_auto = self.workfolder / "decomposition_auto"
        self.decomposition_results = self.workfolder / "decomposition_results"
        self.analysis = self.workfolder / "analysis"

    def list_original_files(self) -> List[Path]:
        """List original imported files."""
        if not self.original_files.exists():
            return []
        return sorted(self.original_files.glob("*.mat"))

    def list_final_json_files(self) -> List[Path]:
        """List final cleaned JSON files."""
        if not self.decomposition_results.exists():
            return []
        return sorted(self.decomposition_results.glob("*_cleaned.json"))

    def list_decomposition_files(self) -> List[Path]:
        """List decomposition JSON files (before cleaning)."""
        if not self.decomposition_auto.exists():
            return []
        # Exclude metadata files
        exclude = ['decomposition_mapping.json', 'multigrid_groupings.json',
                   'covisi_pre_filter_report.json', 'covisi_post_validation_report.json']
        return sorted([f for f in self.decomposition_auto.glob("*.json")
                      if f.name not in exclude])

    def get_metadata_files(self) -> Dict[str, Path]:
        """Get paths to all metadata JSON files."""
        return {{
            'decomposition_mapping': self.decomposition_auto / "decomposition_mapping.json",
            'multigrid_groupings': self.decomposition_auto / "multigrid_groupings.json",
            'covisi_pre_filter': self.decomposition_auto / "covisi_pre_filter_report.json",
            'covisi_post_validation': self.decomposition_auto / "covisi_post_validation_report.json"
        }}

    def list_analysis_files(self) -> Dict[str, List[Path]]:
        """List analysis output files (RMS, CoVISI, etc.)."""
        if not self.analysis.exists():
            return {{}}

        return {{
            'summary_plots': sorted(self.analysis.glob("*_summary.png")),
            'channel_plots': sorted(self.analysis.glob("*_per_channel.png")),
            'reports': sorted(self.analysis.glob("*_report.csv")),
            'summaries': sorted(self.analysis.glob("*_summary.txt"))
        }}


class MetadataReader:
    """Read and parse pipeline metadata."""

    def __init__(self, paths: WorkfolderPaths):
        self.paths = paths

    def _read_json(self, path: Path) -> Optional[Dict]:
        """Helper to read JSON file."""
        if not path.exists():
            return None
        try:
            with open(path, 'r', encoding='utf-8') as f:
                return json.load(f)
        except Exception as e:
            print(f"Warning: Failed to read {{path.name}}: {{e}}")
            return None

    def get_decomposition_mapping(self) -> Optional[Dict]:
        """Read decomposition file mapping."""
        path = self.paths.get_metadata_files()['decomposition_mapping']
        return self._read_json(path)

    def get_multigrid_groupings(self) -> Optional[Dict]:
        """Read multi-grid grouping configuration."""
        path = self.paths.get_metadata_files()['multigrid_groupings']
        return self._read_json(path)

    def get_covisi_pre_filter(self) -> Optional[Dict]:
        """Read CoVISI pre-filter report."""
        path = self.paths.get_metadata_files()['covisi_pre_filter']
        return self._read_json(path)

    def get_covisi_post_validation(self) -> Optional[Dict]:
        """Read CoVISI post-validation report."""
        path = self.paths.get_metadata_files()['covisi_post_validation']
        return self._read_json(path)

    def get_rms_quality_data(self, json_file: Path) -> Optional[Dict]:
        """Read RMS quality data for a specific file."""
        # RMS JSON files are stored in cropped_signal folder
        base_name = json_file.stem.replace('_cleaned', '')
        rms_json = self.paths.cropped_signal / f"{{base_name}}_rms.json"
        return self._read_json(rms_json)

    def check_skip_marker(self, folder: Path) -> bool:
        """Check if a step was skipped."""
        skip_marker = folder / ".skip_marker.json"
        return skip_marker.exists()


class PipelineSummary:
    """Generate human-readable pipeline summary."""

    STEP_NAMES = {{
        1: "Open File(s)",
        2: "Grid Association",
        3: "Line Noise Removal",
        4: "RMS Quality Analysis",
        5: "Define ROI",
        6: "Channel Selection",
        7: "Decomposition Results",
        8: "Multi-Grid Configuration",
        9: "CoVISI Pre-Filter",
        10: "MUEdit Cleaning",
        11: "CoVISI Post-Validation",
        12: "Final Results"
    }}

    def __init__(self, paths: WorkfolderPaths, reader: MetadataReader):
        self.paths = paths
        self.reader = reader

    def get_completed_steps(self) -> List[Tuple[int, str, str]]:
        """
        Returns list of (step_num, step_name, status).

        Status: "Completed", "Skipped", or "Not Performed"
        """
        steps = []

        # Step 1: Original files (mandatory)
        status = "Completed" if len(self.paths.list_original_files()) > 0 else "Not Performed"
        steps.append((1, self.STEP_NAMES[1], status))

        # Step 2: Grid association
        has_files = len(list(self.paths.associated_grids.glob("*.mat"))) > 0 if self.paths.associated_grids.exists() else False
        is_skipped = self.reader.check_skip_marker(self.paths.associated_grids)
        status = "Skipped" if is_skipped else ("Completed" if has_files else "Not Performed")
        steps.append((2, self.STEP_NAMES[2], status))

        # Step 3: Line noise cleaned
        has_files = len(list(self.paths.line_noise_cleaned.glob("*.mat"))) > 0 if self.paths.line_noise_cleaned.exists() else False
        is_skipped = self.reader.check_skip_marker(self.paths.line_noise_cleaned)
        status = "Skipped" if is_skipped else ("Completed" if has_files else "Not Performed")
        steps.append((3, self.STEP_NAMES[3], status))

        # Step 4: RMS analysis
        has_files = len(self.paths.list_analysis_files().get('summary_plots', [])) > 0
        is_skipped = self.reader.check_skip_marker(self.paths.analysis)
        status = "Skipped" if is_skipped else ("Completed" if has_files else "Not Performed")
        steps.append((4, self.STEP_NAMES[4], status))

        # Step 5: ROI definition
        has_files = len(list(self.paths.cropped_signal.glob("*.mat"))) > 0 if self.paths.cropped_signal.exists() else False
        is_skipped = self.reader.check_skip_marker(self.paths.cropped_signal)
        status = "Skipped" if is_skipped else ("Completed" if has_files else "Not Performed")
        steps.append((5, self.STEP_NAMES[5], status))

        # Step 6: Channel selection
        has_files = len(list(self.paths.channelselection.glob("*.mat"))) > 0 if self.paths.channelselection.exists() else False
        status = "Completed" if has_files else "Not Performed"
        steps.append((6, self.STEP_NAMES[6], status))

        # Step 7: Decomposition
        has_files = len(self.paths.list_decomposition_files()) > 0
        status = "Completed" if has_files else "Not Performed"
        steps.append((7, self.STEP_NAMES[7], status))

        # Step 8: Multi-grid config
        mapping = self.reader.get_multigrid_groupings()
        status = "Completed" if mapping is not None else "Not Performed"
        steps.append((8, self.STEP_NAMES[8], status))

        # Step 9: CoVISI pre-filter
        pre_report = self.reader.get_covisi_pre_filter()
        if pre_report:
            status = "Skipped" if pre_report.get('filtering_skipped', False) else "Completed"
        else:
            status = "Not Performed"
        steps.append((9, self.STEP_NAMES[9], status))

        # Step 10: MUEdit cleaning
        has_edited = len(list(self.paths.decomposition_auto.glob("*.mat_edited.mat"))) > 0 if self.paths.decomposition_auto.exists() else False
        status = "Completed" if has_edited else "Not Performed"
        steps.append((10, self.STEP_NAMES[10], status))

        # Step 11: CoVISI post-validation
        post_report = self.reader.get_covisi_post_validation()
        status = "Completed" if post_report is not None else "Not Performed"
        steps.append((11, self.STEP_NAMES[11], status))

        # Step 12: Final results
        has_files = len(self.paths.list_final_json_files()) > 0
        status = "Completed" if has_files else "Not Performed"
        steps.append((12, self.STEP_NAMES[12], status))

        return steps

    def print_full_summary(self):
        """Print formatted pipeline summary to console."""
        print("=" * 70)
        print("HD-sEMG Processing Pipeline Summary")
        print("=" * 70)
        print()

        steps = self.get_completed_steps()

        for step_num, step_name, status in steps:
            symbol = "✓" if status == "Completed" else ("⏭" if status == "Skipped" else "○")
            print(f"  Step {{step_num:2d}}: {{symbol}} {{step_name:<30s}} [{{status}}]")

        print()
        print("=" * 70)
        print("File Counts:")
        print("=" * 70)
        print(f"  Original files: {{len(self.paths.list_original_files())}}")
        print(f"  Decomposition files: {{len(self.paths.list_decomposition_files())}}")
        print(f"  Final cleaned files: {{len(self.paths.list_final_json_files())}}")
        print()

    def print_quality_metrics(self):
        """Print quality assessment results."""
        print("=" * 70)
        print("Quality Metrics")
        print("=" * 70)
        print()

        # RMS Quality
        analysis_files = self.paths.list_analysis_files()
        if analysis_files.get('reports'):
            print(f"✓ RMS Quality Analysis: {{len(analysis_files['reports'])}} report(s) generated")
        else:
            print("○ RMS Quality Analysis: Not performed")

        # CoVISI Pre-Filter
        pre_report = self.reader.get_covisi_pre_filter()
        if pre_report:
            if pre_report.get('filtering_skipped', False):
                print("⏭ CoVISI Pre-Filter: Skipped by user")
            else:
                removed = pre_report.get('removed_mu_indices', [])
                total_mus = pre_report.get('total_mus_before', 'N/A')
                print(f"✓ CoVISI Pre-Filter: {{len(removed)}} / {{total_mus}} motor units filtered")
                print(f"  Threshold: {{pre_report.get('threshold', 30.0)}}%")
        else:
            print("○ CoVISI Pre-Filter: Not performed")

        # CoVISI Post-Validation
        post_report = self.reader.get_covisi_post_validation()
        if post_report:
            print("✓ CoVISI Post-Validation: Quality verified after MUedit cleaning")
        else:
            print("○ CoVISI Post-Validation: Not performed")

        print()

    def get_processing_info(self) -> Dict:
        """Get structured processing information."""
        pre_report = self.reader.get_covisi_pre_filter()
        post_report = self.reader.get_covisi_post_validation()

        return {{
            'total_original_files': len(self.paths.list_original_files()),
            'total_final_files': len(self.paths.list_final_json_files()),
            'covisi_pre_threshold': pre_report.get('threshold', 30.0) if pre_report else None,
            'mus_removed_pre': len(pre_report.get('removed_mu_indices', [])) if pre_report else 0,
            'post_validation_performed': post_report is not None,
            'steps_completed': [s for s in self.get_completed_steps() if s[2] == "Completed"]
        }}


def plot_pipeline_overview(summary: PipelineSummary):
    """
    Create visual overview of completed pipeline steps.

    Returns matplotlib Figure or None if matplotlib not available.
    """
    try:
        import matplotlib.pyplot as plt
        import numpy as np
    except ImportError:
        print("matplotlib not available - cannot create plot")
        return None

    steps = summary.get_completed_steps()

    fig, ax = plt.subplots(figsize=(10, 6))

    # Prepare data
    step_nums = [s[0] for s in steps]
    step_names = [s[1] for s in steps]
    statuses = [s[2] for s in steps]

    # Color mapping
    colors = []
    for status in statuses:
        if status == "Completed":
            colors.append('#10b981')  # Green
        elif status == "Skipped":
            colors.append('#f59e0b')  # Orange
        else:
            colors.append('#6b7280')  # Gray

    # Create horizontal bar chart
    y_pos = np.arange(len(step_nums))
    ax.barh(y_pos, [1] * len(step_nums), color=colors, alpha=0.7)

    # Customize
    ax.set_yticks(y_pos)
    ax.set_yticklabels([f"Step {{n}}: {{name}}" for n, name in zip(step_nums, step_names)])
    ax.set_xlabel('Status')
    ax.set_title('HD-sEMG Pipeline Processing Steps')
    ax.set_xlim(0, 1)
    ax.set_xticks([])

    # Add legend
    from matplotlib.patches import Patch
    legend_elements = [
        Patch(facecolor='#10b981', label='Completed'),
        Patch(facecolor='#f59e0b', label='Skipped'),
        Patch(facecolor='#6b7280', label='Not Performed')
    ]
    ax.legend(handles=legend_elements, loc='lower right')

    plt.tight_layout()
    return fig


def plot_covisi_comparison(reader: MetadataReader):
    """
    Compare CoVISI values before and after cleaning.

    Returns matplotlib Figure or None if data not available.
    """
    try:
        import matplotlib.pyplot as plt
        import numpy as np
    except ImportError:
        print("matplotlib not available - cannot create plot")
        return None

    pre_report = reader.get_covisi_pre_filter()
    post_report = reader.get_covisi_post_validation()

    if not pre_report and not post_report:
        print("No CoVISI data available for comparison")
        return None

    fig, ax = plt.subplots(figsize=(10, 6))

    # Extract CoVISI values if available
    if pre_report and 'mu_covisi_values' in pre_report:
        mu_covisi = pre_report['mu_covisi_values']
        if mu_covisi:
            indices = [item[0] for item in mu_covisi]
            values = [item[1] for item in mu_covisi]
            ax.scatter(indices, values, alpha=0.6, label='Pre-Filter', s=50)

    # Add threshold line
    threshold = pre_report.get('threshold', 30.0) if pre_report else 30.0
    ax.axhline(y=threshold, color='r', linestyle='--', label=f'Threshold ({{threshold}}%)')

    ax.set_xlabel('Motor Unit Index')
    ax.set_ylabel('CoVISI (%)')
    ax.set_title('CoVISI Quality Assessment')
    ax.legend()
    ax.grid(True, alpha=0.3)

    plt.tight_layout()
    return fig
'''


# ============================================================================
# NOTEBOOK CELL GENERATION
# ============================================================================

def get_notebook_cells(workfolder: str) -> List[Dict]:
    """
    Generate all notebook cells with content.

    Returns list of cell dicts with 'cell_type' and 'source' keys.
    """
    cells = []

    # Cell 1: Title & Introduction (Markdown)
    cells.append({
        'cell_type': 'markdown',
        'source': '''# HD-sEMG Analysis Notebook

**Generated by hdsemg-pipe**

This notebook provides a starting point for analyzing the cleaned motor unit data from your processing pipeline.

## Contents
1. Setup & Data Loading
2. Pipeline Summary
3. Motor Unit Visualizations
4. Motor Unit Analysis
5. Custom Analysis (template)
6. Export Results'''
    })

    # Cell 2: Setup & Imports (Code)
    cells.append({
        'cell_type': 'code',
        'source': '''# Standard libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path
import json

# Import helper module (generated alongside this notebook)
import sys
WORKFOLDER = Path.cwd()
if str(WORKFOLDER) not in sys.path:
    sys.path.insert(0, str(WORKFOLDER))

from workfolder_analysis_helper import WorkfolderPaths, MetadataReader, PipelineSummary
from workfolder_analysis_helper import plot_pipeline_overview, plot_covisi_comparison

# openhdemg (optional but recommended)
try:
    import openhdemg.library as emg
    import openhdemg.plotemg as plot
    OPENHDEMG_AVAILABLE = True
    print("✓ openhdemg available")
except ImportError:
    OPENHDEMG_AVAILABLE = False
    print("⚠ openhdemg not available - install with: pip install openhdemg")

# Matplotlib settings
%matplotlib inline
plt.rcParams['figure.figsize'] = (12, 6)
plt.rcParams['font.size'] = 10'''
    })

    # Cell 3: Initialize Paths (Code)
    cells.append({
        'cell_type': 'code',
        'source': '''# Initialize workfolder paths
paths = WorkfolderPaths(WORKFOLDER)
reader = MetadataReader(paths)
summary = PipelineSummary(paths, reader)

# List available files
final_files = paths.list_final_json_files()
print(f"Found {len(final_files)} cleaned JSON file(s):")
for f in final_files:
    print(f"  - {f.name}")'''
    })

    # Cell 4: Pipeline Summary (Code)
    cells.append({
        'cell_type': 'code',
        'source': '''# Display pipeline processing summary
summary.print_full_summary()
print("\\n")
summary.print_quality_metrics()'''
    })

    # Cell 5: Section Header - Load Data (Markdown)
    cells.append({
        'cell_type': 'markdown',
        'source': '''## 1. Load Motor Unit Data

Load all cleaned JSON files using openhdemg.'''
    })

    # Cell 6: Load All JSON Files (Code)
    cells.append({
        'cell_type': 'code',
        'source': '''# Load all cleaned decomposition files
emgfiles = []

if OPENHDEMG_AVAILABLE:
    for json_path in final_files:
        try:
            emgfile = emg.emg_from_json(str(json_path))
            emgfiles.append({
                'filename': json_path.name,
                'path': json_path,
                'data': emgfile
            })
            print(f"✓ Loaded {json_path.name}: {emgfile['NUMBER_OF_MUS']} MUs, "
                  f"{emgfile['FSAMP']} Hz, "
                  f"{len(emgfile['RAW_SIGNAL'])} samples")
        except Exception as e:
            print(f"✗ Failed to load {json_path.name}: {e}")
else:
    print("Cannot load files - openhdemg not available")

print(f"\\nTotal loaded: {len(emgfiles)} file(s)")'''
    })

    # Cell 7: Section Header - Visualizations (Markdown)
    cells.append({
        'cell_type': 'markdown',
        'source': '''## 2. Motor Unit Visualizations

### Visualizations:
1. **Discharge Times (plot_mupulses)** - Rasterplot showing MU firing patterns
2. **Firing Rate (plot_idr)** - Instantaneous discharge rate over time
3. **Motor Unit Action Potentials (plot_muaps)** - MUAP morphology comparison
4. **Reference Signal (plot_refsig)** - Force/activation context'''
    })

    # Cell 8: Plot Discharge Times (Code)
    cells.append({
        'cell_type': 'code',
        'source': '''# Visualization 1: Discharge Times (Rasterplot)
if OPENHDEMG_AVAILABLE and len(emgfiles) > 0:
    # Plot first file as example
    emgfile = emgfiles[0]['data']
    filename = emgfiles[0]['filename']

    fig = plot.plot_mupulses(
        emgfile=emgfile,
        linewidths=0.8,
        title=f"Motor Unit Discharge Times: {filename}"
    )
    plt.show()
else:
    print("Cannot plot - no data loaded")'''
    })

    # Cell 9: Plot Firing Rates (Code)
    cells.append({
        'cell_type': 'code',
        'source': '''# Visualization 2: Instantaneous Discharge Rate
if OPENHDEMG_AVAILABLE and len(emgfiles) > 0:
    emgfile = emgfiles[0]['data']
    filename = emgfiles[0]['filename']

    fig = plot.plot_idr(
        emgfile=emgfile,
        munumber="all",
        title=f"Instantaneous Discharge Rate: {filename}"
    )
    plt.show()'''
    })

    # Cell 10: Plot MUAPs (Code)
    cells.append({
        'cell_type': 'code',
        'source': '''# Visualization 3: Motor Unit Action Potentials
if OPENHDEMG_AVAILABLE and len(emgfiles) > 0:
    emgfile = emgfiles[0]['data']
    filename = emgfiles[0]['filename']

    # Plot MUAPs for all motor units (overlay)
    try:
        fig = plot.plot_muaps(
            emgfile=emgfile,
            munumber="all",
            channel=0,  # First channel
            title=f"Motor Unit Action Potentials: {filename}"
        )
        plt.show()
    except Exception as e:
        print(f"Note: MUAP plotting requires spike-triggered averaged data: {e}")'''
    })

    # Cell 11: Plot Reference Signal (Code)
    cells.append({
        'cell_type': 'code',
        'source': '''# Visualization 4: Reference Signal (Force/Activation)
if OPENHDEMG_AVAILABLE and len(emgfiles) > 0:
    emgfile = emgfiles[0]['data']
    filename = emgfiles[0]['filename']

    fig = plot.plot_refsig(
        emgfile=emgfile,
        ylabel="Force",
        title=f"Reference Signal: {filename}"
    )
    plt.show()'''
    })

    # Cell 12: Section Header - Analysis (Markdown)
    cells.append({
        'cell_type': 'markdown',
        'source': '''## 3. Motor Unit Analysis

### Analysis Focus Areas:
1. **Recruitment Analysis** - Recruitment thresholds and timing
2. **Firing Rate Statistics** - Mean/peak rates, CoVISI verification
3. **Motor Unit Properties** - MU characteristics summary
4. **Quality Metrics** - SIL values, CoVISI comparison'''
    })

    # Cell 13: Recruitment Analysis (Code)
    cells.append({
        'cell_type': 'code',
        'source': '''# Analysis 1: Recruitment Analysis
print("=" * 60)
print("Recruitment Analysis")
print("=" * 60)

if OPENHDEMG_AVAILABLE and len(emgfiles) > 0:
    for emg_entry in emgfiles:
        emgfile = emg_entry['data']
        filename = emg_entry['filename']

        print(f"\\n{filename}:")
        print(f"  Number of Motor Units: {emgfile['NUMBER_OF_MUS']}")

        # Extract recruitment times (first spike of each MU)
        recruitment_times = []
        for mu_idx in range(emgfile['NUMBER_OF_MUS']):
            mupulses = emgfile['MUPULSES'][mu_idx]
            if len(mupulses) > 0:
                first_spike_sample = mupulses[0]
                first_spike_time = first_spike_sample / emgfile['FSAMP']
                recruitment_times.append((mu_idx, first_spike_time))

        if recruitment_times:
            # Sort by recruitment time
            recruitment_times.sort(key=lambda x: x[1])
            print(f"  Recruitment Order (by time):")
            for rank, (mu_idx, rec_time) in enumerate(recruitment_times, 1):
                print(f"    Rank {rank}: MU {mu_idx} at {rec_time:.2f}s")'''
    })

    # Cell 14: Firing Rate Statistics (Code)
    cells.append({
        'cell_type': 'code',
        'source': '''# Analysis 2: Firing Rate Statistics & CoVISI Verification
print("=" * 60)
print("Firing Rate Statistics")
print("=" * 60)

if OPENHDEMG_AVAILABLE and len(emgfiles) > 0:
    for emg_entry in emgfiles:
        emgfile = emg_entry['data']
        filename = emg_entry['filename']

        print(f"\\n{filename}:")

        # Compute firing rate statistics for each MU
        for mu_idx in range(emgfile['NUMBER_OF_MUS']):
            mupulses = emgfile['MUPULSES'][mu_idx]
            if len(mupulses) > 1:
                # Calculate inter-spike intervals (ISI)
                isi = np.diff(mupulses) / emgfile['FSAMP']  # in seconds
                instantaneous_rates = 1.0 / isi  # Hz

                mean_rate = np.mean(instantaneous_rates)
                peak_rate = np.max(instantaneous_rates)

                print(f"  MU {mu_idx}: Mean Rate = {mean_rate:.2f} Hz, Peak Rate = {peak_rate:.2f} Hz")

# Display CoVISI post-validation results
print("\\n" + "=" * 60)
print("CoVISI Post-Validation")
print("=" * 60)
post_covisi = reader.get_covisi_post_validation()
if post_covisi:
    print("✓ CoVISI validation performed")
    # You can extract and display specific metrics from the report here
else:
    print("⚠ CoVISI post-validation not performed")'''
    })

    # Cell 15: Motor Unit Properties Summary (Code)
    cells.append({
        'cell_type': 'code',
        'source': '''# Analysis 3: Motor Unit Properties Summary
print("=" * 60)
print("Motor Unit Properties Summary")
print("=" * 60)

properties_list = []

if OPENHDEMG_AVAILABLE and len(emgfiles) > 0:
    for emg_entry in emgfiles:
        emgfile = emg_entry['data']
        filename = emg_entry['filename']

        for mu_idx in range(emgfile['NUMBER_OF_MUS']):
            mupulses = emgfile['MUPULSES'][mu_idx]

            if len(mupulses) > 1:
                # Calculate properties
                n_spikes = len(mupulses)
                duration = (mupulses[-1] - mupulses[0]) / emgfile['FSAMP']
                isi = np.diff(mupulses) / emgfile['FSAMP']
                mean_firing_rate = np.mean(1.0 / isi) if len(isi) > 0 else 0

                properties_list.append({
                    'File': filename,
                    'MU_Index': mu_idx,
                    'N_Spikes': n_spikes,
                    'Duration_s': duration,
                    'Mean_Firing_Rate_Hz': mean_firing_rate
                })

    # Create DataFrame for easy analysis
    df_properties = pd.DataFrame(properties_list)
    print(df_properties.describe())

    # Save to CSV
    output_csv = WORKFOLDER / "motor_unit_properties.csv"
    df_properties.to_csv(output_csv, index=False)
    print(f"\\n✓ Properties saved to: {output_csv}")'''
    })

    # Cell 16: Quality Metrics Comparison (Code)
    cells.append({
        'cell_type': 'code',
        'source': '''# Analysis 4: Quality Metrics Overview
print("=" * 60)
print("Quality Metrics Overview")
print("=" * 60)

# SIL values from decomposition
if OPENHDEMG_AVAILABLE and len(emgfiles) > 0:
    print("\\nSilhouette (SIL) Values:")
    for emg_entry in emgfiles:
        emgfile = emg_entry['data']
        filename = emg_entry['filename']

        if 'ACCURACY' in emgfile and emgfile['ACCURACY'] is not None:
            sil_values = emgfile['ACCURACY'].values.flatten()
            print(f"  {filename}:")
            print(f"    Mean SIL: {np.mean(sil_values):.3f}")
            print(f"    Min SIL: {np.min(sil_values):.3f}")
            print(f"    Max SIL: {np.max(sil_values):.3f}")

# CoVISI comparison
print("\\n" + "=" * 60)
print("CoVISI Pre/Post Comparison")
print("=" * 60)

pre_report = reader.get_covisi_pre_filter()
post_report = reader.get_covisi_post_validation()

if pre_report:
    print(f"Pre-Filter:")
    removed = pre_report.get('removed_mu_indices', [])
    print(f"  Motor units removed: {len(removed)}")
    print(f"  Threshold: {pre_report.get('threshold', 30.0)}%")

if post_report:
    print("Post-Validation: Quality verified after MUedit cleaning")'''
    })

    # Cell 17: Section Header - Custom Analysis (Markdown)
    cells.append({
        'cell_type': 'markdown',
        'source': '''## 4. Custom Analysis Section

**Template for your own analysis**

Use this section to add your custom analysis code. Examples:
- Cross-correlations between motor units
- Coherence analysis with reference signal
- Custom recruitment pattern analysis
- Export to custom formats (Excel, MATLAB, etc.)'''
    })

    # Cell 18: Custom Analysis Template (Code)
    cells.append({
        'cell_type': 'code',
        'source': '''# Your custom analysis code here

# Example: Export to Excel
if len(emgfiles) > 0:
    # Create Excel workbook with multiple sheets
    output_excel = WORKFOLDER / "custom_analysis.xlsx"

    # Example: Export discharge times to Excel
    # with pd.ExcelWriter(output_excel, engine='openpyxl') as writer:
    #     for emg_entry in emgfiles:
    #         # Your export logic
    #         pass

    print("Custom analysis placeholder - add your code here")'''
    })

    # Cell 19: Section Header - Export (Markdown)
    cells.append({
        'cell_type': 'markdown',
        'source': '''## 5. Export Results

Save your analysis results to files for publication or further processing.'''
    })

    # Cell 20: Export Results (Code)
    cells.append({
        'cell_type': 'code',
        'source': '''# Export analysis results

# Example exports:
# 1. Motor unit properties DataFrame (already saved above)
# 2. Custom figures
# 3. Summary statistics

print("=" * 60)
print("Export Summary")
print("=" * 60)
print(f"Workfolder: {WORKFOLDER}")
print(f"Files available:")
print(f"  - motor_unit_properties.csv (MU statistics)")
print(f"  - [Add your custom exports here]")
print("\\n✓ Analysis complete!")'''
    })

    return cells
