"""
Templates for Jupyter Notebook Export

Contains the helper module template and notebook cell generation functions.
"""
from pathlib import Path
from typing import List, Dict, Optional, Tuple
import json


# ============================================================================
# HELPER MODULE TEMPLATE
# ============================================================================

HELPER_MODULE_TEMPLATE = '''"""
HD-sEMG Workfolder Analysis Helper

Auto-generated by hdsemg-pipe for Jupyter notebook analysis.
Provides easy access to folder paths, metadata, and pipeline summary.
"""
import json
import re
from pathlib import Path
from typing import List, Dict, Optional, Tuple
import os


class WorkfolderPaths:
    """Easy access to all workfolder paths and files."""

    def __init__(self, workfolder: str):
        self.workfolder = Path(workfolder)
        self.original_files = self.workfolder / "original_files"
        self.associated_grids = self.workfolder / "associated_grids"
        self.line_noise_cleaned = self.workfolder / "line_noise_cleaned"
        self.cropped_signal = self.workfolder / "cropped_signal"
        self.channelselection = self.workfolder / "channelselection"
        self.decomposition_auto = self.workfolder / "decomposition_auto"
        self.decomposition_results = self.workfolder / "decomposition_results"
        self.analysis = self.workfolder / "analysis"

    def list_original_files(self) -> List[Path]:
        """List original imported files."""
        if not self.original_files.exists():
            return []
        return sorted(self.original_files.glob("*.mat"))

    def list_final_json_files(self) -> List[Path]:
        """List final cleaned JSON files."""
        if not self.decomposition_results.exists():
            return []
        return sorted(self.decomposition_results.glob("*_cleaned.json"))

    def list_decomposition_files(self) -> List[Path]:
        """List decomposition JSON files (before cleaning)."""
        if not self.decomposition_auto.exists():
            return []
        # Exclude metadata files
        exclude = ['decomposition_mapping.json', 'multigrid_groupings.json',
                   'covisi_pre_filter_report.json', 'covisi_post_validation_report.json']
        return sorted([f for f in self.decomposition_auto.glob("*.json")
                      if f.name not in exclude])

    def get_metadata_files(self) -> Dict[str, Path]:
        """Get paths to all metadata JSON files."""
        return {{
            'decomposition_mapping': self.decomposition_auto / "decomposition_mapping.json",
            'multigrid_groupings': self.decomposition_auto / "multigrid_groupings.json",
            'covisi_pre_filter': self.decomposition_auto / "covisi_pre_filter_report.json",
            'covisi_post_validation': self.decomposition_auto / "covisi_post_validation_report.json"
        }}

    def list_analysis_files(self) -> Dict[str, List[Path]]:
        """List analysis output files (RMS, CoVISI, etc.)."""
        if not self.analysis.exists():
            return {{}}

        return {{
            'summary_plots': sorted(self.analysis.glob("*_summary.png")),
            'channel_plots': sorted(self.analysis.glob("*_per_channel.png")),
            'reports': sorted(self.analysis.glob("*_report.csv")),
            'summaries': sorted(self.analysis.glob("*_summary.txt"))
        }}

    def find_protocol_file(self) -> Optional[Path]:
        """Find the hdsemg-trail protocol file (*_protokoll.txt) in the workfolder root."""
        protocol_files = sorted(self.workfolder.glob("*_protokoll.txt"))
        if protocol_files:
            return protocol_files[0]
        return None


class MetadataReader:
    """Read and parse pipeline metadata."""

    def __init__(self, paths: WorkfolderPaths):
        self.paths = paths

    def _read_json(self, path: Path) -> Optional[Dict]:
        """Helper to read JSON file."""
        if not path.exists():
            return None
        try:
            with open(path, 'r', encoding='utf-8') as f:
                return json.load(f)
        except Exception as e:
            print(f"Warning: Failed to read {{path.name}}: {{e}}")
            return None

    def get_decomposition_mapping(self) -> Optional[Dict]:
        """Read decomposition file mapping."""
        path = self.paths.get_metadata_files()['decomposition_mapping']
        return self._read_json(path)

    def get_multigrid_groupings(self) -> Optional[Dict]:
        """Read multi-grid grouping configuration."""
        path = self.paths.get_metadata_files()['multigrid_groupings']
        return self._read_json(path)

    def get_covisi_pre_filter(self) -> Optional[Dict]:
        """Read CoVISI pre-filter report."""
        path = self.paths.get_metadata_files()['covisi_pre_filter']
        return self._read_json(path)

    def get_covisi_post_validation(self) -> Optional[Dict]:
        """Read CoVISI post-validation report."""
        path = self.paths.get_metadata_files()['covisi_post_validation']
        return self._read_json(path)

    def get_rms_quality_data(self, json_file: Path) -> Optional[Dict]:
        """Read RMS quality data for a specific file."""
        # RMS JSON files are stored in cropped_signal folder
        base_name = json_file.stem.replace('_cleaned', '')
        rms_json = self.paths.cropped_signal / f"{{base_name}}_rms.json"
        return self._read_json(rms_json)

    def check_skip_marker(self, folder: Path) -> bool:
        """Check if a step was skipped."""
        skip_marker = folder / ".skip_marker.json"
        return skip_marker.exists()


class PipelineSummary:
    """Generate human-readable pipeline summary."""

    STEP_NAMES = {{
        1: "Open File(s)",
        2: "Grid Association",
        3: "Line Noise Removal",
        4: "RMS Quality Analysis",
        5: "Define ROI",
        6: "Channel Selection",
        7: "Decomposition Results",
        8: "Multi-Grid Configuration",
        9: "CoVISI Pre-Filter",
        10: "MUEdit Cleaning",
        11: "CoVISI Post-Validation",
        12: "Final Results"
    }}

    def __init__(self, paths: WorkfolderPaths, reader: MetadataReader):
        self.paths = paths
        self.reader = reader

    def get_completed_steps(self) -> List[Tuple[int, str, str]]:
        """
        Returns list of (step_num, step_name, status).

        Status: "Completed", "Skipped", or "Not Performed"
        """
        steps = []

        # Step 1: Original files (mandatory)
        status = "Completed" if len(self.paths.list_original_files()) > 0 else "Not Performed"
        steps.append((1, self.STEP_NAMES[1], status))

        # Step 2: Grid association
        has_files = len(list(self.paths.associated_grids.glob("*.mat"))) > 0 if self.paths.associated_grids.exists() else False
        is_skipped = self.reader.check_skip_marker(self.paths.associated_grids)
        status = "Skipped" if is_skipped else ("Completed" if has_files else "Not Performed")
        steps.append((2, self.STEP_NAMES[2], status))

        # Step 3: Line noise cleaned
        has_files = len(list(self.paths.line_noise_cleaned.glob("*.mat"))) > 0 if self.paths.line_noise_cleaned.exists() else False
        is_skipped = self.reader.check_skip_marker(self.paths.line_noise_cleaned)
        status = "Skipped" if is_skipped else ("Completed" if has_files else "Not Performed")
        steps.append((3, self.STEP_NAMES[3], status))

        # Step 4: RMS analysis
        has_files = len(self.paths.list_analysis_files().get('summary_plots', [])) > 0
        is_skipped = self.reader.check_skip_marker(self.paths.analysis)
        status = "Skipped" if is_skipped else ("Completed" if has_files else "Not Performed")
        steps.append((4, self.STEP_NAMES[4], status))

        # Step 5: ROI definition
        has_files = len(list(self.paths.cropped_signal.glob("*.mat"))) > 0 if self.paths.cropped_signal.exists() else False
        is_skipped = self.reader.check_skip_marker(self.paths.cropped_signal)
        status = "Skipped" if is_skipped else ("Completed" if has_files else "Not Performed")
        steps.append((5, self.STEP_NAMES[5], status))

        # Step 6: Channel selection
        has_files = len(list(self.paths.channelselection.glob("*.mat"))) > 0 if self.paths.channelselection.exists() else False
        status = "Completed" if has_files else "Not Performed"
        steps.append((6, self.STEP_NAMES[6], status))

        # Step 7: Decomposition
        has_files = len(self.paths.list_decomposition_files()) > 0
        status = "Completed" if has_files else "Not Performed"
        steps.append((7, self.STEP_NAMES[7], status))

        # Step 8: Multi-grid config
        mapping = self.reader.get_multigrid_groupings()
        status = "Completed" if mapping is not None else "Not Performed"
        steps.append((8, self.STEP_NAMES[8], status))

        # Step 9: CoVISI pre-filter
        pre_report = self.reader.get_covisi_pre_filter()
        if pre_report:
            status = "Skipped" if pre_report.get('filtering_skipped', False) else "Completed"
        else:
            status = "Not Performed"
        steps.append((9, self.STEP_NAMES[9], status))

        # Step 10: MUEdit cleaning
        has_edited = len(list(self.paths.decomposition_auto.glob("*.mat_edited.mat"))) > 0 if self.paths.decomposition_auto.exists() else False
        status = "Completed" if has_edited else "Not Performed"
        steps.append((10, self.STEP_NAMES[10], status))

        # Step 11: CoVISI post-validation
        post_report = self.reader.get_covisi_post_validation()
        status = "Completed" if post_report is not None else "Not Performed"
        steps.append((11, self.STEP_NAMES[11], status))

        # Step 12: Final results
        has_files = len(self.paths.list_final_json_files()) > 0
        status = "Completed" if has_files else "Not Performed"
        steps.append((12, self.STEP_NAMES[12], status))

        return steps

    def print_full_summary(self):
        """Print formatted pipeline summary to console."""
        print("=" * 70)
        print("HD-sEMG Processing Pipeline Summary")
        print("=" * 70)
        print()

        steps = self.get_completed_steps()

        for step_num, step_name, status in steps:
            symbol = "✓" if status == "Completed" else ("⏭" if status == "Skipped" else "○")
            print(f"  Step {{step_num:2d}}: {{symbol}} {{step_name:<30s}} [{{status}}]")

        print()
        print("=" * 70)
        print("File Counts:")
        print("=" * 70)
        print(f"  Original files: {{len(self.paths.list_original_files())}}")
        print(f"  Decomposition files: {{len(self.paths.list_decomposition_files())}}")
        print(f"  Final cleaned files: {{len(self.paths.list_final_json_files())}}")
        print()

    def print_quality_metrics(self):
        """Print quality assessment results."""
        print("=" * 70)
        print("Quality Metrics")
        print("=" * 70)
        print()

        # RMS Quality
        analysis_files = self.paths.list_analysis_files()
        if analysis_files.get('reports'):
            print(f"✓ RMS Quality Analysis: {{len(analysis_files['reports'])}} report(s) generated")
        else:
            print("○ RMS Quality Analysis: Not performed")

        # CoVISI Pre-Filter
        pre_report = self.reader.get_covisi_pre_filter()
        if pre_report:
            if pre_report.get('filtering_skipped', False):
                print("⏭ CoVISI Pre-Filter: Skipped by user")
            else:
                removed = pre_report.get('removed_mu_indices', [])
                total_mus = pre_report.get('total_mus_before', 'N/A')
                print(f"✓ CoVISI Pre-Filter: {{len(removed)}} / {{total_mus}} motor units filtered")
                print(f"  Threshold: {{pre_report.get('threshold', 30.0)}}%")
        else:
            print("○ CoVISI Pre-Filter: Not performed")

        # CoVISI Post-Validation
        post_report = self.reader.get_covisi_post_validation()
        if post_report:
            print("✓ CoVISI Post-Validation: Quality verified after MUedit cleaning")
        else:
            print("○ CoVISI Post-Validation: Not performed")

        print()

    def get_processing_info(self) -> Dict:
        """Get structured processing information."""
        pre_report = self.reader.get_covisi_pre_filter()
        post_report = self.reader.get_covisi_post_validation()

        return {{
            'total_original_files': len(self.paths.list_original_files()),
            'total_final_files': len(self.paths.list_final_json_files()),
            'covisi_pre_threshold': pre_report.get('threshold', 30.0) if pre_report else None,
            'mus_removed_pre': len(pre_report.get('removed_mu_indices', [])) if pre_report else 0,
            'post_validation_performed': post_report is not None,
            'steps_completed': [s for s in self.get_completed_steps() if s[2] == "Completed"]
        }}


def plot_pipeline_overview(summary: PipelineSummary):
    """
    Create visual overview of completed pipeline steps.

    Returns matplotlib Figure or None if matplotlib not available.
    """
    try:
        import matplotlib.pyplot as plt
        import numpy as np
    except ImportError:
        print("matplotlib not available - cannot create plot")
        return None

    steps = summary.get_completed_steps()

    fig, ax = plt.subplots(figsize=(10, 6))

    # Prepare data
    step_nums = [s[0] for s in steps]
    step_names = [s[1] for s in steps]
    statuses = [s[2] for s in steps]

    # Color mapping
    colors = []
    for status in statuses:
        if status == "Completed":
            colors.append('#10b981')  # Green
        elif status == "Skipped":
            colors.append('#f59e0b')  # Orange
        else:
            colors.append('#6b7280')  # Gray

    # Create horizontal bar chart
    y_pos = np.arange(len(step_nums))
    ax.barh(y_pos, [1] * len(step_nums), color=colors, alpha=0.7)

    # Customize
    ax.set_yticks(y_pos)
    ax.set_yticklabels([f"Step {{n}}: {{name}}" for n, name in zip(step_nums, step_names)])
    ax.set_xlabel('Status')
    ax.set_title('HD-sEMG Pipeline Processing Steps')
    ax.set_xlim(0, 1)
    ax.set_xticks([])

    # Add legend
    from matplotlib.patches import Patch
    legend_elements = [
        Patch(facecolor='#10b981', label='Completed'),
        Patch(facecolor='#f59e0b', label='Skipped'),
        Patch(facecolor='#6b7280', label='Not Performed')
    ]
    ax.legend(handles=legend_elements, loc='lower right')

    plt.tight_layout()
    return fig


def plot_covisi_comparison(reader: MetadataReader):
    """
    Compare CoVISI values before and after cleaning.

    Returns matplotlib Figure or None if data not available.
    """
    try:
        import matplotlib.pyplot as plt
        import numpy as np
    except ImportError:
        print("matplotlib not available - cannot create plot")
        return None

    pre_report = reader.get_covisi_pre_filter()
    post_report = reader.get_covisi_post_validation()

    if not pre_report and not post_report:
        print("No CoVISI data available for comparison")
        return None

    fig, ax = plt.subplots(figsize=(10, 6))

    # Extract CoVISI values if available
    if pre_report and 'mu_covisi_values' in pre_report:
        mu_covisi = pre_report['mu_covisi_values']
        if mu_covisi:
            indices = [item[0] for item in mu_covisi]
            values = [item[1] for item in mu_covisi]
            ax.scatter(indices, values, alpha=0.6, label='Pre-Filter', s=50)

    # Add threshold line
    threshold = pre_report.get('threshold', 30.0) if pre_report else 30.0
    ax.axhline(y=threshold, color='r', linestyle='--', label=f'Threshold ({{threshold}}%)')

    ax.set_xlabel('Motor Unit Index')
    ax.set_ylabel('CoVISI (%)')
    ax.set_title('CoVISI Quality Assessment')
    ax.legend()
    ax.grid(True, alpha=0.3)

    plt.tight_layout()
    return fig


class ProtocolParser:
    """
    Parse hdsemg-trail protocol files (*_protokoll.txt) and map EMG file
    groups to experimental conditions based on the randomization order.

    Study design (crossover):
        Block1 (Baseline) -> Block2 (Pre) -> Training1 -> Block3 (Post-T1)
        -> Washout -> Block4 (Post-Washout) -> Training2 -> Block5 (Post-T2)
        -> Rest -> Block6 (Final)

    The randomization field determines which training mode (CON/EXZ) was first.
    """

    CONDITION_MAPS = {{
        'CON first': {{
            'Block1': {{'condition': 'Baseline', 'training_mode': None}},
            'Block2': {{'condition': 'Pre_Intervention', 'training_mode': None}},
            'Block3': {{'condition': 'Post_CON', 'training_mode': 'CON'}},
            'Block4': {{'condition': 'Post_Washout', 'training_mode': None}},
            'Block5': {{'condition': 'Post_EXZ', 'training_mode': 'EXZ'}},
            'Block6': {{'condition': 'Final', 'training_mode': None}},
        }},
        'EXZ first': {{
            'Block1': {{'condition': 'Baseline', 'training_mode': None}},
            'Block2': {{'condition': 'Pre_Intervention', 'training_mode': None}},
            'Block3': {{'condition': 'Post_EXZ', 'training_mode': 'EXZ'}},
            'Block4': {{'condition': 'Post_Washout', 'training_mode': None}},
            'Block5': {{'condition': 'Post_CON', 'training_mode': 'CON'}},
            'Block6': {{'condition': 'Final', 'training_mode': None}},
        }},
    }}

    # Ordered list of conditions for consistent output
    CONDITION_ORDER = [
        'Baseline', 'Pre_Intervention', 'Post_CON', 'Post_EXZ',
        'Post_Washout', 'Final',
    ]

    def __init__(self, paths: WorkfolderPaths):
        self.paths = paths
        self._protocol = None

    def find_protocol_file(self) -> Optional[Path]:
        """Find the protocol file in the workfolder root."""
        return self.paths.find_protocol_file()

    def parse(self) -> Optional[Dict]:
        """
        Parse the protocol file and return structured data.

        Returns dict with keys: 'file', 'metadata', 'steps'
        or None if no protocol file is found.
        """
        protocol_path = self.find_protocol_file()
        if not protocol_path:
            print("No protocol file (*_protokoll.txt) found in workfolder.")
            return None

        with open(protocol_path, 'r', encoding='utf-8') as f:
            content = f.read()

        self._protocol = {{
            'file': protocol_path.name,
            'metadata': self._parse_metadata(content),
            'steps': self._parse_steps(content),
        }}
        return self._protocol

    def _parse_metadata(self, content: str) -> Dict:
        """Extract key-value pairs from the Metadaten section."""
        metadata = {{}}
        in_metadata = False

        for line in content.split('\\n'):
            stripped = line.strip()

            if stripped.startswith('Metadaten:'):
                in_metadata = True
                continue
            if stripped.startswith('Schritte:') or stripped.startswith('====='):
                if in_metadata:
                    break

            if in_metadata and ':' in stripped:
                key, _, value = stripped.partition(':')
                key = key.strip()
                value = value.strip()
                if key and not key.startswith(('•', '▸', '✓', '⏱', '⌛', '📋')):
                    metadata[key] = value

        return metadata

    def _parse_steps(self, content: str) -> List[Dict]:
        """Extract structured data for each protocol step."""
        steps = []
        step_pattern = re.compile(
            r'\\[Schritt\\s+(\\d+)\\]\\s+(.+?)\\s+\\(([a-z_0-9]+)\\)'
        )

        current_step = None
        current_section = None  # 'inputs', 'notes', 'measurements'

        for line in content.split('\\n'):
            stripped = line.strip()

            # Match step header
            m = step_pattern.match(stripped)
            if m:
                if current_step:
                    steps.append(current_step)
                current_step = {{
                    'number': int(m.group(1)),
                    'name': m.group(2).strip(),
                    'step_id': m.group(3),
                    'inputs': {{}},
                    'notes': '',
                }}
                current_section = None
                continue

            if current_step is None:
                continue

            # Detect sections
            if stripped.startswith('Eingaben:'):
                current_section = 'inputs'
                continue
            elif stripped.startswith('Notizen:') or stripped.startswith('📝 Notizen:'):
                current_section = 'notes'
                continue
            elif stripped.startswith('Wiederholbare Messungen:'):
                current_section = 'measurements'
                continue
            elif stripped.startswith(('⏱', '✓', '⌛', '📋')):
                current_section = None
                continue

            # Parse input entries: "• Key: Value"
            if current_section == 'inputs' and stripped.startswith('•'):
                entry = stripped.lstrip('• ').strip()
                if ':' in entry:
                    key, _, value = entry.partition(':')
                    current_step['inputs'][key.strip()] = value.strip()

            # Parse notes (free text lines)
            if current_section == 'notes' and stripped:
                if current_step['notes']:
                    current_step['notes'] += ' '
                current_step['notes'] += stripped

        # Don't forget last step
        if current_step:
            steps.append(current_step)

        return steps

    def get_randomization(self) -> Optional[str]:
        """Get randomization order ('CON first' or 'EXZ first')."""
        if not self._protocol:
            self.parse()
        if not self._protocol:
            return None
        return self._protocol['metadata'].get('randomization')

    def get_metadata(self) -> Dict:
        """Get all protocol metadata."""
        if not self._protocol:
            self.parse()
        if not self._protocol:
            return {{}}
        return self._protocol['metadata']

    def get_step_by_id(self, step_id: str) -> Optional[Dict]:
        """Get a specific protocol step by its step_id (e.g. 'ft_block1')."""
        if not self._protocol:
            self.parse()
        if not self._protocol:
            return None
        for step in self._protocol['steps']:
            if step['step_id'] == step_id:
                return step
        return None

    def get_condition_map(self) -> Dict[str, Dict]:
        """
        Get Block -> condition mapping based on the randomization order.

        Returns dict like:
            {{'Block1': {{'condition': 'Baseline', 'training_mode': None}}, ...}}
        """
        randomization = self.get_randomization()
        if randomization and randomization in self.CONDITION_MAPS:
            return self.CONDITION_MAPS[randomization]
        print(f"Warning: Unknown randomization '{{randomization}}', defaulting to 'CON first'")
        return self.CONDITION_MAPS['CON first']

    def create_condition_groups(self, emgfile_groups: Dict) -> Dict:
        """
        Create condition-based meta-grouping from emgfile groups.

        Takes the output of create_emgfile_groups() and maps each group to an
        experimental condition based on the Block number in the file basename
        and the randomization order from the protocol.

        Args:
            emgfile_groups: Output dict from create_emgfile_groups()

        Returns:
            Dict with structure:
                {{
                    'conditions': {{
                        'Baseline': {{
                            'block': 'Block1',
                            'training_mode': None,
                            'tracking_types': {{
                                'Trapezoid': [group1, ...],
                                'Pyramid': [group2, ...]
                            }}
                        }},
                        ...
                    }},
                    'unmatched': [...],
                    'randomization': str,
                    'metadata': dict
                }}
        """
        condition_map = self.get_condition_map()

        # Initialize condition groups in defined order
        conditions = {{}}
        for block_key, info in condition_map.items():
            cond = info['condition']
            if cond not in conditions:
                conditions[cond] = {{
                    'block': block_key,
                    'training_mode': info['training_mode'],
                    'tracking_types': {{}},
                }}

        unmatched = []

        # Process multi-file groups
        for group in emgfile_groups.get('groups', []):
            self._assign_group(group, group.get('file_base', ''), condition_map, conditions, unmatched)

        # Process ungrouped (single) files as individual groups
        for entry in emgfile_groups.get('ungrouped', []):
            filename = entry.get('filename', '')
            single_group = {{
                'name': filename,
                'muscle': self._extract_muscle(filename),
                'file_base': self._extract_basename(filename),
                'files': [entry],
                'count': 1,
                'concatenated': entry.get('data'),
            }}
            self._assign_group(single_group, single_group['file_base'], condition_map, conditions, unmatched)

        return {{
            'conditions': conditions,
            'unmatched': unmatched,
            'randomization': self.get_randomization(),
            'metadata': self.get_metadata(),
        }}

    def _assign_group(self, group, file_base, condition_map, conditions, unmatched):
        """Assign a single group to a condition based on its Block number."""
        block_match = re.search(r'Block(\\d+)', file_base)
        if not block_match:
            unmatched.append(group)
            return

        block_str = f"Block{{block_match.group(1)}}"
        block_info = condition_map.get(block_str)
        if not block_info:
            unmatched.append(group)
            return

        condition = block_info['condition']

        # Determine tracking type from file_base
        # Filenames use 'Trap' (short) or 'Trapezoid' (full) for trapezoid tracking
        tracking_type = 'Other'
        if 'Trap' in file_base:
            tracking_type = 'Trapezoid'
        elif 'Pyramid' in file_base:
            tracking_type = 'Pyramid'

        if tracking_type not in conditions[condition]['tracking_types']:
            conditions[condition]['tracking_types'][tracking_type] = []
        conditions[condition]['tracking_types'][tracking_type].append(group)

    @staticmethod
    def _extract_basename(filename: str) -> str:
        """Extract file basename (mirrors decomposition_export logic)."""
        name = os.path.basename(filename)
        for ext in ['.json', '.pkl', '.mat']:
            if name.endswith(ext):
                name = name[:-len(ext)]
        suffixes = [
            '_covisi_filtered_cleaned', '_covisi_filtered',
            '_muedit', '_edited', '_cleaned',
        ]
        for suffix in suffixes:
            if name.endswith(suffix):
                name = name[:-len(suffix)]
        # Remove muscle name (last CamelCase part)
        parts = name.split('_')
        for part in reversed(parts):
            if len(part) > 1 and any(c.isupper() for c in part) and any(c.islower() for c in part):
                if name.endswith(part):
                    name = name[:-len(part)].rstrip('_')
                break
        # Remove grid dimension pattern
        name = re.sub(r'_\\d+mm_\\d+x\\d+(_\\d+)?', '', name)
        return name

    @staticmethod
    def _extract_muscle(filename: str) -> Optional[str]:
        """Extract muscle name from filename (mirrors decomposition_export logic)."""
        basename = os.path.basename(filename)
        suffixes_to_remove = [
            '_covisi_filtered.json', '.json', '.pkl', '.mat',
        ]
        for suffix in suffixes_to_remove:
            if basename.endswith(suffix):
                basename = basename[:-len(suffix)]
                break
        parts = basename.split('_')
        for part in reversed(parts):
            if len(part) > 1 and any(c.isupper() for c in part) and any(c.islower() for c in part):
                return part
        return None

    def print_condition_summary(self, condition_result: Dict):
        """Print a formatted summary of the condition-based grouping."""
        randomization = condition_result.get('randomization', 'Unknown')
        metadata = condition_result.get('metadata', {{}})

        print("=" * 70)
        print("Condition Grouping Summary")
        print("=" * 70)
        print(f"  PID: {{metadata.get('pid', 'N/A')}}")
        print(f"  Session: {{metadata.get('session_type', 'N/A')}}")
        print(f"  Randomization: {{randomization}}")
        print()

        for cond_name in self.CONDITION_ORDER:
            cond_data = condition_result['conditions'].get(cond_name)
            if not cond_data:
                continue

            training = cond_data.get('training_mode')
            training_str = f" [{{training}}]" if training else ""
            block = cond_data.get('block', '?')

            total_groups = sum(
                len(groups) for groups in cond_data['tracking_types'].values()
            )

            print(f"{{cond_name}}{{training_str}} ({{block}}): {{total_groups}} group(s)")

            for tracking_type, groups in sorted(cond_data['tracking_types'].items()):
                print(f"  {{tracking_type}}:")
                for group in groups:
                    n_files = group.get('count', len(group.get('files', [])))
                    concat = group.get('concatenated')
                    n_mus = concat['NUMBER_OF_MUS'] if concat and 'NUMBER_OF_MUS' in concat else '?'
                    muscles = set()
                    for f in group.get('files', []):
                        m = f.get('data', {{}}).get('MUSCLE') or group.get('muscle', '')
                        if m:
                            muscles.add(m)
                    muscle_str = ', '.join(muscles) if muscles else group.get('muscle', '')
                    print(f"    - {{group['name']}}: {{n_files}} file(s), {{n_mus}} MUs [{{muscle_str}}]")

            print()

        unmatched = condition_result.get('unmatched', [])
        if unmatched:
            print(f"Unmatched: {{len(unmatched)}} group(s) could not be assigned to a condition")
            for group in unmatched:
                print(f"  - {{group.get('name', 'unknown')}}")
'''


# ============================================================================
# NOTEBOOK CELL GENERATION
# ============================================================================

def get_notebook_cells(workfolder: str) -> List[Dict]:
    """
    Generate all notebook cells with content.

    Returns list of cell dicts with 'cell_type' and 'source' keys.
    """
    cells = []

    # Cell 1: Title & Introduction (Markdown)
    cells.append({
        'cell_type': 'markdown',
        'source': '''# HD-sEMG Analysis Notebook

**Generated by hdsemg-pipe**

This notebook provides a starting point for analyzing the cleaned motor unit data from your processing pipeline.

## Contents
1. Data Loading
2. Protocol & Condition Grouping
3. Motor Unit Visualizations
4. Motor Unit Analysis
5. Condition Comparison (CON vs EXZ)
6. Custom Analysis (template)
7. Export Results'''
    })

    # Cell 2: Setup & Imports (Code)
    cells.append({
        'cell_type': 'code',
        'source': '''# Standard libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path
import json

# Import helper module (generated alongside this notebook)
import sys
WORKFOLDER = Path.cwd()
if str(WORKFOLDER) not in sys.path:
    sys.path.insert(0, str(WORKFOLDER))

from workfolder_analysis_helper import WorkfolderPaths, MetadataReader, PipelineSummary, ProtocolParser
from workfolder_analysis_helper import plot_pipeline_overview, plot_covisi_comparison

# openhdemg (optional but recommended)
try:
    from openhdemg.library import plotemg as plot
    from openhdemg.library import openfiles as emg
    from openhdemg.library import tools as tools
    OPENHDEMG_AVAILABLE = True
    print("✓ openhdemg available")
except ImportError:
    OPENHDEMG_AVAILABLE = False
    print("⚠ openhdemg not available - install with: pip install openhdemg")

# Matplotlib settings
%matplotlib inline
plt.rcParams['figure.figsize'] = (12, 6)
plt.rcParams['font.size'] = 10'''
    })

    # Cell 3: Initialize Paths (Code)
    cells.append({
        'cell_type': 'code',
        'source': '''# Initialize workfolder paths
paths = WorkfolderPaths(WORKFOLDER)
reader = MetadataReader(paths)
summary = PipelineSummary(paths, reader)

# List available files
final_files = paths.list_final_json_files()
print(f"Found {len(final_files)} cleaned JSON file(s):")
for f in final_files:
    print(f"  - {f.name}")'''
    })

    # Cell 4: Pipeline Summary (Code)
    cells.append({
        'cell_type': 'code',
        'source': '''# Display pipeline processing summary
summary.print_full_summary()
print("\\n")
summary.print_quality_metrics()'''
    })

    # Cell 5: Section Header - Load Data (Markdown)
    cells.append({
        'cell_type': 'markdown',
        'source': '''## 1. Load Motor Unit Data

Load all cleaned JSON files using openhdemg.'''
    })

    # Cell 6: Load All JSON Files (Code)
    cells.append({
        'cell_type': 'code',
        'source': '''# Load all cleaned decomposition files
emgfiles = []

if OPENHDEMG_AVAILABLE:
    for json_path in final_files:
        try:
            emgfile = emg.emg_from_json(str(json_path))
            emgfile = tools.sort_mus(emgfile)
            emgfiles.append({
                'filename': json_path.name,
                'path': json_path,
                'data': emgfile
            })
            print(f"✓ Loaded {json_path.name}: {emgfile['NUMBER_OF_MUS']} MUs, "
                  f"{emgfile['FSAMP']} Hz, "
                  f"{len(emgfile['RAW_SIGNAL'])} samples")
        except Exception as e:
            print(f"✗ Failed to load {json_path.name}: {e}")
else:
    print("Cannot load files - openhdemg not available")

print(f"\\nTotal loaded: {len(emgfiles)} file(s)")'''
    })

    # Cell 7: Section Header - Protocol & Condition Grouping (Markdown)
    cells.append({
        'cell_type': 'markdown',
        'source': '''## 2. Protocol & Condition Grouping

Parse the hdsemg-trail protocol file to map EMG file groups to experimental conditions
(Baseline, Pre-Intervention, Post-CON, Post-EXZ, etc.) based on the randomization order.

This creates a **grouping of groupings**: `create_emgfile_groups` groups files by
(basename, muscle), then the protocol parser maps those groups to the study conditions.'''
    })

    # Cell 8: Parse Protocol (Code)
    cells.append({
        'cell_type': 'code',
        'source': '''# Parse hdsemg-trail protocol
protocol_parser = ProtocolParser(paths)
protocol = protocol_parser.parse()

if protocol:
    meta = protocol['metadata']
    print(f"Protocol file: {protocol['file']}")
    print(f"  PID: {meta.get('pid', 'N/A')}")
    print(f"  Session: {meta.get('session_type', 'N/A')}")
    print(f"  Randomization: {meta.get('randomization', 'N/A')}")
    print(f"  Steps parsed: {len(protocol['steps'])}")

    # Show training block details
    for step in protocol['steps']:
        if step['step_id'].startswith('training_block'):
            mode = step['inputs'].get('Kontraktionsmodus', 'N/A')
            sets = step['inputs'].get('Sätze abgeschlossen', '?')
            borg = step['inputs'].get('Borg CR10 Anstrengung', '?')
            print(f"\\n  {step['name']} ({step['step_id']}):")
            print(f"    Mode: {mode}")
            print(f"    Sets: {sets}, Borg: {borg}")
            if step['notes']:
                print(f"    Notes: {step['notes']}")
else:
    print("No protocol file found - condition grouping will not be available")'''
    })

    # Cell 9: Create Condition Groups (Code)
    cells.append({
        'cell_type': 'code',
        'source': '''# Create EMG file groups and map to experimental conditions
if OPENHDEMG_AVAILABLE and len(emgfiles) > 0 and protocol:
    from hdsemg_pipe.actions.decomposition_export import create_emgfile_groups

    # Step 1: Group files by (basename, muscle)
    groups_result = create_emgfile_groups(emgfiles, strategy='file_and_muscle', concatenate=True)
    print(f"File grouping: {groups_result['summary']['group_count']} groups, "
          f"{groups_result['summary']['ungrouped_files']} ungrouped\\n")

    # Step 2: Map groups to experimental conditions via protocol
    condition_result = protocol_parser.create_condition_groups(groups_result)
    protocol_parser.print_condition_summary(condition_result)
else:
    condition_result = None
    if not protocol:
        print("Skipped: no protocol file available")
    else:
        print("Skipped: no EMG files loaded")'''
    })

    # Cell 10: Access Condition Data Template (Code)
    cells.append({
        'cell_type': 'code',
        'source': '''# Access condition data for analysis
# Example: iterate over conditions and tracking types

if condition_result:
    for cond_name, cond_data in condition_result['conditions'].items():
        training_mode = cond_data.get('training_mode')
        block = cond_data.get('block')

        for tracking_type, groups in cond_data['tracking_types'].items():
            for group in groups:
                emgfile = group.get('concatenated')
                if emgfile is None:
                    continue

                n_mus = emgfile['NUMBER_OF_MUS']
                print(f"{cond_name} | {tracking_type} | {group['muscle']}: "
                      f"{n_mus} MUs ({group['count']} file(s))")

    # Example: compare Post-CON vs Post-EXZ Trapezoid groups
    # post_con_trap = condition_result['conditions'].get('Post_CON', {}).get('tracking_types', {}).get('Trapezoid', [])
    # post_exz_trap = condition_result['conditions'].get('Post_EXZ', {}).get('tracking_types', {}).get('Trapezoid', [])'''
    })

    # Cell 11: Section Header - Visualizations (Markdown)
    cells.append({
        'cell_type': 'markdown',
        'source': '''## 3. Motor Unit Visualizations

### Visualizations:
1. **Discharge Times (plot_mupulses)** - Rasterplot showing MU firing patterns
2. **Firing Rate (plot_idr)** - Instantaneous discharge rate over time
3. **Motor Unit Action Potentials (plot_muaps)** - MUAP morphology comparison
4. **Reference Signal (plot_refsig)** - Force/activation context'''
    })

    # Cell 8: Plot Discharge Times (Code)
    cells.append({
        'cell_type': 'code',
        'source': '''# Visualization 1: Discharge Times (Rasterplot)
if OPENHDEMG_AVAILABLE and len(emgfiles) > 0:
    # Plot first file as example
    emgfile = emgfiles[0]['data']
    filename = emgfiles[0]['filename']

    fig = plot.plot_mupulses(
        emgfile=emgfile,
        linewidths=0.8,
    )
    plt.show()
else:
    print("Cannot plot - no data loaded")'''
    })

    # Cell 9: Plot Firing Rates (Code)
    cells.append({
        'cell_type': 'code',
        'source': '''# Visualization 2: Instantaneous Discharge Rate
if OPENHDEMG_AVAILABLE and len(emgfiles) > 0:
    emgfile = emgfiles[0]['data']
    filename = emgfiles[0]['filename']

    fig = plot.plot_idr(
        emgfile=emgfile,
        munumber="all",
    )
    plt.show()'''
    })

    # Cell 10: Plot MUAPs (Code)
    cells.append({
        'cell_type': 'code',
        'source': '''# Visualization 3: Motor Unit Action Potentials
if OPENHDEMG_AVAILABLE and len(emgfiles) > 0:
    emgfile = emgfiles[0]['data']
    filename = emgfiles[0]['filename']

    # Plot MUAPs for all motor units (overlay)
    try:
        fig = plot.plot_muaps(
            emgfile=emgfile,
            munumber="all",
            channel=0,  # First channel
        )
        plt.show()
    except Exception as e:
        print(f"Note: MUAP plotting requires spike-triggered averaged data: {e}")'''
    })

    # Cell 11: Plot Reference Signal (Code)
    cells.append({
        'cell_type': 'code',
        'source': '''# Visualization 4: Reference Signal (Force/Activation)
if OPENHDEMG_AVAILABLE and len(emgfiles) > 0:
    emgfile = emgfiles[0]['data']
    filename = emgfiles[0]['filename']

    fig = plot.plot_refsig(
        emgfile=emgfile,
        ylabel="Force",
    )
    plt.show()'''
    })

    # Cell 12: Section Header - Analysis (Markdown)
    cells.append({
        'cell_type': 'markdown',
        'source': '''## 4. Motor Unit Analysis

### Analysis Focus Areas:
1. **Recruitment Analysis** - Recruitment thresholds and timing
2. **Firing Rate Statistics** - Mean/peak rates, CoVISI verification
3. **Motor Unit Properties** - MU characteristics summary
4. **Quality Metrics** - SIL values, CoVISI comparison'''
    })

    # Cell 13: Recruitment Analysis (Code)
    cells.append({
        'cell_type': 'code',
        'source': '''# Analysis 1: Recruitment Analysis
print("=" * 60)
print("Recruitment Analysis")
print("=" * 60)

if OPENHDEMG_AVAILABLE and len(emgfiles) > 0:
    for emg_entry in emgfiles:
        emgfile = emg_entry['data']
        filename = emg_entry['filename']

        print(f"\\n{filename}:")
        print(f"  Number of Motor Units: {emgfile['NUMBER_OF_MUS']}")

        # Extract recruitment times (first spike of each MU)
        recruitment_times = []
        for mu_idx in range(emgfile['NUMBER_OF_MUS']):
            mupulses = emgfile['MUPULSES'][mu_idx]
            if len(mupulses) > 0:
                first_spike_sample = mupulses[0]
                first_spike_time = first_spike_sample / emgfile['FSAMP']
                recruitment_times.append((mu_idx, first_spike_time))

        if recruitment_times:
            # Sort by recruitment time
            recruitment_times.sort(key=lambda x: x[1])
            print(f"  Recruitment Order (by time):")
            for rank, (mu_idx, rec_time) in enumerate(recruitment_times, 1):
                print(f"    Rank {rank}: MU {mu_idx} at {rec_time:.2f}s")'''
    })

    # Cell 14: Firing Rate Statistics (Code)
    cells.append({
        'cell_type': 'code',
        'source': '''# Analysis 2: Firing Rate Statistics & CoVISI Verification
print("=" * 60)
print("Firing Rate Statistics")
print("=" * 60)

if OPENHDEMG_AVAILABLE and len(emgfiles) > 0:
    for emg_entry in emgfiles:
        emgfile = emg_entry['data']
        filename = emg_entry['filename']

        print(f"\\n{filename}:")

        # Compute firing rate statistics for each MU
        for mu_idx in range(emgfile['NUMBER_OF_MUS']):
            mupulses = emgfile['MUPULSES'][mu_idx]
            if len(mupulses) > 1:
                # Calculate inter-spike intervals (ISI)
                isi = np.diff(mupulses) / emgfile['FSAMP']  # in seconds
                instantaneous_rates = 1.0 / isi  # Hz

                mean_rate = np.mean(instantaneous_rates)
                peak_rate = np.max(instantaneous_rates)

                print(f"  MU {mu_idx}: Mean Rate = {mean_rate:.2f} Hz, Peak Rate = {peak_rate:.2f} Hz")

# Display CoVISI post-validation results
print("\\n" + "=" * 60)
print("CoVISI Post-Validation")
print("=" * 60)
post_covisi = reader.get_covisi_post_validation()
if post_covisi:
    print("✓ CoVISI validation performed")
    # You can extract and display specific metrics from the report here
else:
    print("⚠ CoVISI post-validation not performed")'''
    })

    # Cell 15: Motor Unit Properties Summary (Code)
    cells.append({
        'cell_type': 'code',
        'source': '''# Analysis 3: Motor Unit Properties Summary
print("=" * 60)
print("Motor Unit Properties Summary")
print("=" * 60)

properties_list = []

if OPENHDEMG_AVAILABLE and len(emgfiles) > 0:
    for emg_entry in emgfiles:
        emgfile = emg_entry['data']
        filename = emg_entry['filename']

        for mu_idx in range(emgfile['NUMBER_OF_MUS']):
            mupulses = emgfile['MUPULSES'][mu_idx]

            if len(mupulses) > 1:
                # Calculate properties
                n_spikes = len(mupulses)
                duration = (mupulses[-1] - mupulses[0]) / emgfile['FSAMP']
                isi = np.diff(mupulses) / emgfile['FSAMP']
                mean_firing_rate = np.mean(1.0 / isi) if len(isi) > 0 else 0

                properties_list.append({
                    'File': filename,
                    'MU_Index': mu_idx,
                    'N_Spikes': n_spikes,
                    'Duration_s': duration,
                    'Mean_Firing_Rate_Hz': mean_firing_rate
                })

    # Create DataFrame for easy analysis
    df_properties = pd.DataFrame(properties_list)
    print(df_properties.describe())

    # Save to CSV
    output_csv = WORKFOLDER / "motor_unit_properties.csv"
    df_properties.to_csv(output_csv, index=False)
    print(f"\\n✓ Properties saved to: {output_csv}")'''
    })

    # Cell 16: Quality Metrics Comparison (Code)
    cells.append({
        'cell_type': 'code',
        'source': '''# Analysis 4: Quality Metrics Overview
print("=" * 60)
print("Quality Metrics Overview")
print("=" * 60)

# SIL values from decomposition
if OPENHDEMG_AVAILABLE and len(emgfiles) > 0:
    print("\\nSilhouette (SIL) Values:")
    for emg_entry in emgfiles:
        emgfile = emg_entry['data']
        filename = emg_entry['filename']

        if 'ACCURACY' in emgfile and emgfile['ACCURACY'] is not None:
            sil_values = emgfile['ACCURACY'].values.flatten()
            print(f"  {filename}:")
            print(f"    Mean SIL: {np.mean(sil_values):.3f}")
            print(f"    Min SIL: {np.min(sil_values):.3f}")
            print(f"    Max SIL: {np.max(sil_values):.3f}")

# CoVISI comparison
print("\\n" + "=" * 60)
print("CoVISI Pre/Post Comparison")
print("=" * 60)

pre_report = reader.get_covisi_pre_filter()
post_report = reader.get_covisi_post_validation()

if pre_report:
    print(f"Pre-Filter:")
    removed = pre_report.get('removed_mu_indices', [])
    print(f"  Motor units removed: {len(removed)}")
    print(f"  Threshold: {pre_report.get('threshold', 30.0)}%")

if post_report:
    print("Post-Validation: Quality verified after MUedit cleaning")'''
    })

    # ================================================================
    # CONDITION COMPARISON CELLS (CON vs EXZ)
    # ================================================================

    # Condition Comparison Header (Markdown)
    cells.append({
        'cell_type': 'markdown',
        'source': '''## 5. Condition Comparison: CON vs EXZ

Analyse der Effekte akuter konzentrischer und exzentrischer Trainingsinterventionen
auf Motor Unit Eigenschaften.

### Analysierte MU-Parameter:
| Parameter | Beschreibung |
|---|---|
| **MU Yield** | Anzahl identifizierter Motor Units |
| **Mean Discharge Rate (DR)** | Mittlere Entladungsrate (pps) |
| **Peak Discharge Rate** | Maximale Entladungsrate (pps) |
| **Recruitment Threshold (RT)** | Kraft bei Erst-Rekrutierung (%REF) |
| **Derecruitment Threshold (DRT)** | Kraft bei Derekrutierung (%REF) |
| **DR at Recruitment** | Entladungsrate bei Rekrutierung (pps) |
| **DR at Derecruitment** | Entladungsrate bei Derekrutierung (pps) |
| **CoV ISI** | Variationskoeffizient der Interspike-Intervalle (%) |
| **SIL (Accuracy)** | Silhouette-Wert (Dekompositionsqualit\u00e4t) |'''
    })

    # Extract MU Properties into DataFrame (Code)
    cells.append({
        'cell_type': 'code',
        'source': '''# ============================================================
# Extract MU properties from all conditions into a DataFrame
# ============================================================

CONDITION_ORDER = ['Baseline', 'Pre_Intervention', 'Post_CON', 'Post_EXZ', 'Post_Washout', 'Final']

mu_records = []

if condition_result and OPENHDEMG_AVAILABLE:
    for cond_name, cond_data in condition_result['conditions'].items():
        block = cond_data.get('block', '')
        training_mode = cond_data.get('training_mode')

        for tracking_type, groups in cond_data['tracking_types'].items():
            for group in groups:
                emgfile = group.get('concatenated')
                if emgfile is None:
                    continue

                fsamp = emgfile['FSAMP']
                n_mus = emgfile['NUMBER_OF_MUS']
                ref_signal = emgfile['REF_SIGNAL'].values.flatten()
                ref_max = ref_signal.max() if ref_signal.max() > 0 else 1.0

                # SIL / Accuracy values
                sil_values = None
                if 'ACCURACY' in emgfile and emgfile['ACCURACY'] is not None:
                    sil_values = emgfile['ACCURACY'].values.flatten()

                for mu_idx in range(n_mus):
                    mupulses = emgfile['MUPULSES'][mu_idx]
                    if len(mupulses) < 4:
                        continue

                    spikes = np.array(mupulses)

                    # ISI and firing rates
                    isi = np.diff(spikes) / fsamp  # seconds
                    isi = isi[isi > 0.01]  # remove artifacts < 10ms
                    if len(isi) < 2:
                        continue
                    inst_dr = 1.0 / isi  # pps

                    mean_dr = np.mean(inst_dr)
                    peak_dr = np.max(inst_dr)
                    cov_isi = (np.std(isi) / np.mean(isi)) * 100  # %

                    # Recruitment & derecruitment
                    first_spike = spikes[0]
                    last_spike = spikes[-1]
                    rt = (ref_signal[first_spike] / ref_max) * 100 if first_spike < len(ref_signal) else np.nan
                    drt = (ref_signal[last_spike] / ref_max) * 100 if last_spike < len(ref_signal) else np.nan

                    # DR at recruitment (first 5 ISIs) and derecruitment (last 5 ISIs)
                    dr_at_rec = np.mean(inst_dr[:min(5, len(inst_dr))])
                    dr_at_derec = np.mean(inst_dr[max(0, len(inst_dr)-5):])

                    # SIL
                    sil = sil_values[mu_idx] if sil_values is not None and mu_idx < len(sil_values) else np.nan

                    mu_records.append({
                        'condition': cond_name,
                        'block': block,
                        'training_mode': training_mode if training_mode else 'None',
                        'tracking_type': tracking_type,
                        'muscle': group.get('muscle', 'Unknown'),
                        'group_name': group['name'],
                        'mu_idx': mu_idx,
                        'n_spikes': len(spikes),
                        'mean_dr': mean_dr,
                        'peak_dr': peak_dr,
                        'cov_isi': cov_isi,
                        'rt_pct': rt,
                        'drt_pct': drt,
                        'dr_at_rec': dr_at_rec,
                        'dr_at_derec': dr_at_derec,
                        'sil': sil,
                    })

    df_mu = pd.DataFrame(mu_records)
    # Set condition as ordered categorical for correct plot ordering
    df_mu['condition'] = pd.Categorical(df_mu['condition'], categories=CONDITION_ORDER, ordered=True)
    df_mu = df_mu.sort_values('condition')

    print(f"Extracted {len(df_mu)} motor units across {df_mu['condition'].nunique()} conditions")
    print(f"Muscles: {df_mu['muscle'].unique().tolist()}")
    print(f"Tracking types: {df_mu['tracking_type'].unique().tolist()}")
    print()
    print(df_mu.groupby(['condition', 'tracking_type', 'muscle']).agg(
        n_MUs=('mu_idx', 'count'),
        mean_DR=('mean_dr', 'mean'),
        mean_RT=('rt_pct', 'mean'),
    ).round(2))
else:
    df_mu = pd.DataFrame()
    print("No condition data available")'''
    })

    # MU Yield across conditions (Code)
    cells.append({
        'cell_type': 'code',
        'source': '''# ============================================================
# Figure 1: Motor Unit Yield across Conditions
# ============================================================
if len(df_mu) > 0:
    fig, axes = plt.subplots(1, 2, figsize=(14, 5), sharey=True)

    for ax, tracking in zip(axes, ['Trapezoid', 'Pyramid']):
        subset = df_mu[df_mu['tracking_type'] == tracking]
        if subset.empty:
            ax.set_title(f'{tracking} (no data)')
            continue

        # Count MUs per condition and muscle
        counts = subset.groupby(['condition', 'muscle']).size().unstack(fill_value=0)

        counts.plot(kind='bar', ax=ax, width=0.7, edgecolor='black', linewidth=0.5)
        ax.set_title(f'{tracking} Tracking', fontsize=13, fontweight='bold')
        ax.set_xlabel('')
        ax.set_ylabel('Number of Motor Units')
        ax.tick_params(axis='x', rotation=35)
        ax.legend(title='Muscle', fontsize=8)
        ax.grid(axis='y', alpha=0.3)

        # Highlight CON/EXZ blocks
        for i, label in enumerate(ax.get_xticklabels()):
            txt = label.get_text()
            if 'Post_CON' in txt:
                label.set_color('#2563eb')
                label.set_fontweight('bold')
            elif 'Post_EXZ' in txt:
                label.set_color('#dc2626')
                label.set_fontweight('bold')

    fig.suptitle('Motor Unit Yield per Condition', fontsize=14, fontweight='bold', y=1.02)
    plt.tight_layout()
    plt.savefig(WORKFOLDER / 'fig_mu_yield_conditions.png', dpi=150, bbox_inches='tight')
    plt.show()
    print("Saved: fig_mu_yield_conditions.png")'''
    })

    # Mean Discharge Rate comparison (Code)
    cells.append({
        'cell_type': 'code',
        'source': '''# ============================================================
# Figure 2: Mean Discharge Rate across Conditions (Boxplot)
# ============================================================
if len(df_mu) > 0:
    fig, axes = plt.subplots(1, 2, figsize=(14, 5), sharey=True)

    for ax, tracking in zip(axes, ['Trapezoid', 'Pyramid']):
        subset = df_mu[df_mu['tracking_type'] == tracking]
        if subset.empty:
            ax.set_title(f'{tracking} (no data)')
            continue

        # Boxplot: one box per condition, colored by muscle
        muscles = subset['muscle'].unique()
        conditions = [c for c in CONDITION_ORDER if c in subset['condition'].values]
        n_conds = len(conditions)
        width = 0.35
        x = np.arange(n_conds)

        for j, muscle in enumerate(muscles):
            muscle_data = subset[subset['muscle'] == muscle]
            bp_data = [muscle_data[muscle_data['condition'] == c]['mean_dr'].dropna().values
                       for c in conditions]
            positions = x + (j - 0.5 * (len(muscles) - 1)) * width
            bp = ax.boxplot(bp_data, positions=positions, widths=width * 0.85,
                           patch_artist=True, showfliers=True, medianprops=dict(color='black'))
            color = '#3b82f6' if j == 0 else '#f97316'
            for patch in bp['boxes']:
                patch.set_facecolor(color)
                patch.set_alpha(0.6)
            # Legend proxy
            ax.plot([], [], 's', color=color, alpha=0.6, markersize=10, label=muscle)

        ax.set_xticks(x)
        ax.set_xticklabels(conditions, rotation=35, ha='right')
        ax.set_title(f'{tracking} Tracking', fontsize=13, fontweight='bold')
        ax.set_ylabel('Mean Discharge Rate (pps)')
        ax.legend(title='Muscle', fontsize=8)
        ax.grid(axis='y', alpha=0.3)

    fig.suptitle('Mean Discharge Rate across Conditions', fontsize=14, fontweight='bold', y=1.02)
    plt.tight_layout()
    plt.savefig(WORKFOLDER / 'fig_mean_dr_conditions.png', dpi=150, bbox_inches='tight')
    plt.show()
    print("Saved: fig_mean_dr_conditions.png")'''
    })

    # Recruitment Threshold comparison (Code)
    cells.append({
        'cell_type': 'code',
        'source': '''# ============================================================
# Figure 3: Recruitment Threshold across Conditions (Boxplot)
# ============================================================
if len(df_mu) > 0:
    fig, axes = plt.subplots(1, 2, figsize=(14, 5), sharey=True)

    for ax, tracking in zip(axes, ['Trapezoid', 'Pyramid']):
        subset = df_mu[df_mu['tracking_type'] == tracking]
        if subset.empty:
            ax.set_title(f'{tracking} (no data)')
            continue

        muscles = subset['muscle'].unique()
        conditions = [c for c in CONDITION_ORDER if c in subset['condition'].values]
        n_conds = len(conditions)
        width = 0.35
        x = np.arange(n_conds)

        for j, muscle in enumerate(muscles):
            muscle_data = subset[subset['muscle'] == muscle]
            bp_data = [muscle_data[muscle_data['condition'] == c]['rt_pct'].dropna().values
                       for c in conditions]
            positions = x + (j - 0.5 * (len(muscles) - 1)) * width
            bp = ax.boxplot(bp_data, positions=positions, widths=width * 0.85,
                           patch_artist=True, showfliers=True, medianprops=dict(color='black'))
            color = '#3b82f6' if j == 0 else '#f97316'
            for patch in bp['boxes']:
                patch.set_facecolor(color)
                patch.set_alpha(0.6)
            ax.plot([], [], 's', color=color, alpha=0.6, markersize=10, label=muscle)

        ax.set_xticks(x)
        ax.set_xticklabels(conditions, rotation=35, ha='right')
        ax.set_title(f'{tracking} Tracking', fontsize=13, fontweight='bold')
        ax.set_ylabel('Recruitment Threshold (%REF)')
        ax.legend(title='Muscle', fontsize=8)
        ax.grid(axis='y', alpha=0.3)

    fig.suptitle('Recruitment Threshold across Conditions', fontsize=14, fontweight='bold', y=1.02)
    plt.tight_layout()
    plt.savefig(WORKFOLDER / 'fig_rt_conditions.png', dpi=150, bbox_inches='tight')
    plt.show()
    print("Saved: fig_rt_conditions.png")'''
    })

    # Timeline / Line Plot for all metrics (Code)
    cells.append({
        'cell_type': 'code',
        'source': '''# ============================================================
# Figure 4: Timeline Plot - MU Properties across Blocks
# ============================================================
if len(df_mu) > 0:
    metrics = {
        'mean_dr': ('Mean Discharge Rate (pps)', '#2563eb'),
        'peak_dr': ('Peak Discharge Rate (pps)', '#7c3aed'),
        'rt_pct': ('Recruitment Threshold (%REF)', '#059669'),
        'drt_pct': ('Derecruitment Threshold (%REF)', '#d97706'),
    }

    for tracking in ['Trapezoid', 'Pyramid']:
        subset = df_mu[df_mu['tracking_type'] == tracking]
        if subset.empty:
            continue

        fig, axes = plt.subplots(2, 2, figsize=(14, 10))

        for ax, (metric, (label, color)) in zip(axes.flat, metrics.items()):
            for muscle in subset['muscle'].unique():
                m_data = subset[subset['muscle'] == muscle]
                conditions = [c for c in CONDITION_ORDER if c in m_data['condition'].values]

                means = [m_data[m_data['condition'] == c][metric].mean() for c in conditions]
                sems = [m_data[m_data['condition'] == c][metric].sem() for c in conditions]

                style = '-o' if 'Lateralis' in muscle else '-s'
                ax.errorbar(range(len(conditions)), means, yerr=sems, fmt=style,
                           capsize=4, capthick=1.5, linewidth=2, markersize=7,
                           label=muscle, alpha=0.85)

            ax.set_xticks(range(len(conditions)))
            ax.set_xticklabels(conditions, rotation=35, ha='right', fontsize=9)
            ax.set_ylabel(label, fontsize=10)
            ax.legend(fontsize=8)
            ax.grid(alpha=0.3)

            # Shade training periods
            for i, c in enumerate(conditions):
                if 'Post_CON' in c:
                    ax.axvspan(i - 0.4, i + 0.4, alpha=0.08, color='blue')
                elif 'Post_EXZ' in c:
                    ax.axvspan(i - 0.4, i + 0.4, alpha=0.08, color='red')

        fig.suptitle(f'{tracking} Tracking - MU Properties Timeline (Mean \\u00b1 SEM)',
                     fontsize=14, fontweight='bold')
        plt.tight_layout()
        plt.savefig(WORKFOLDER / f'fig_timeline_{tracking.lower()}.png', dpi=150, bbox_inches='tight')
        plt.show()
        print(f"Saved: fig_timeline_{tracking.lower()}.png")'''
    })

    # RT vs DR Scatter (Code)
    cells.append({
        'cell_type': 'code',
        'source': '''# ============================================================
# Figure 5: Recruitment Threshold vs Discharge Rate (Onion Skin)
# ============================================================
if len(df_mu) > 0:
    focus_conditions = ['Pre_Intervention', 'Post_CON', 'Post_EXZ']
    cond_colors = {'Pre_Intervention': '#6b7280', 'Post_CON': '#2563eb', 'Post_EXZ': '#dc2626'}
    cond_markers = {'Pre_Intervention': 'o', 'Post_CON': 's', 'Post_EXZ': '^'}

    for tracking in ['Trapezoid', 'Pyramid']:
        subset = df_mu[(df_mu['tracking_type'] == tracking) &
                       (df_mu['condition'].isin(focus_conditions))]
        if subset.empty:
            continue

        muscles = subset['muscle'].unique()
        fig, axes = plt.subplots(1, len(muscles), figsize=(7 * len(muscles), 6), squeeze=False)

        for ax, muscle in zip(axes[0], muscles):
            m_data = subset[subset['muscle'] == muscle]

            for cond in focus_conditions:
                c_data = m_data[m_data['condition'] == cond]
                if c_data.empty:
                    continue
                ax.scatter(c_data['rt_pct'], c_data['mean_dr'],
                          c=cond_colors[cond], marker=cond_markers[cond],
                          s=60, alpha=0.7, edgecolors='black', linewidth=0.5,
                          label=cond)

            ax.set_xlabel('Recruitment Threshold (%REF)', fontsize=11)
            ax.set_ylabel('Mean Discharge Rate (pps)', fontsize=11)
            ax.set_title(f'{muscle}', fontsize=12, fontweight='bold')
            ax.legend(fontsize=9)
            ax.grid(alpha=0.3)

        fig.suptitle(f'{tracking} - RT vs DR (Onion Skin Pattern)',
                     fontsize=14, fontweight='bold', y=1.02)
        plt.tight_layout()
        plt.savefig(WORKFOLDER / f'fig_rt_vs_dr_{tracking.lower()}.png', dpi=150, bbox_inches='tight')
        plt.show()
        print(f"Saved: fig_rt_vs_dr_{tracking.lower()}.png")'''
    })

    # Summary statistics table (Code)
    cells.append({
        'cell_type': 'code',
        'source': '''# ============================================================
# Table: Summary Statistics per Condition
# ============================================================
if len(df_mu) > 0:
    summary_cols = ['mean_dr', 'peak_dr', 'rt_pct', 'drt_pct', 'dr_at_rec', 'dr_at_derec', 'cov_isi', 'sil']
    col_labels = {
        'mean_dr': 'Mean DR (pps)',
        'peak_dr': 'Peak DR (pps)',
        'rt_pct': 'RT (%REF)',
        'drt_pct': 'DRT (%REF)',
        'dr_at_rec': 'DR@Rec (pps)',
        'dr_at_derec': 'DR@Derec (pps)',
        'cov_isi': 'CoV ISI (%)',
        'sil': 'SIL',
    }

    for tracking in ['Trapezoid', 'Pyramid']:
        subset = df_mu[df_mu['tracking_type'] == tracking]
        if subset.empty:
            continue

        print(f"\\n{'='*80}")
        print(f"  {tracking} Tracking - Summary Statistics (Mean \\u00b1 SD)")
        print(f"{'='*80}")

        for muscle in sorted(subset['muscle'].unique()):
            m_data = subset[subset['muscle'] == muscle]
            print(f"\\n  {muscle}:")
            print(f"  {'Condition':<20s} {'n':>4s}", end='')
            for col in summary_cols:
                print(f"  {col_labels[col]:>14s}", end='')
            print()
            print(f"  {'-'*20} {'-'*4}", end='')
            for _ in summary_cols:
                print(f"  {'-'*14}", end='')
            print()

            for cond in CONDITION_ORDER:
                c_data = m_data[m_data['condition'] == cond]
                if c_data.empty:
                    continue
                n = len(c_data)
                marker = ' *' if cond in ['Post_CON', 'Post_EXZ'] else '  '
                print(f"{marker}{cond:<20s} {n:>4d}", end='')
                for col in summary_cols:
                    vals = c_data[col].dropna()
                    if len(vals) > 0:
                        print(f"  {vals.mean():>6.1f}\\u00b1{vals.std():>5.1f}", end='')
                    else:
                        print(f"  {'N/A':>14s}", end='')
                print()

    # Export full DataFrame to CSV
    csv_path = WORKFOLDER / 'mu_properties_by_condition.csv'
    df_mu.to_csv(csv_path, index=False)
    print(f"\\nExported: {csv_path.name}")'''
    })

    # CON vs EXZ direct comparison (Code)
    cells.append({
        'cell_type': 'code',
        'source': '''# ============================================================
# Figure 6: Direct CON vs EXZ Comparison (Pre -> Post delta)
# ============================================================
if len(df_mu) > 0:
    # Calculate condition means per muscle/tracking for Pre vs Post comparisons
    key_metrics = ['mean_dr', 'peak_dr', 'rt_pct', 'cov_isi']
    metric_labels = {
        'mean_dr': '\\u0394 Mean DR (pps)',
        'peak_dr': '\\u0394 Peak DR (pps)',
        'rt_pct': '\\u0394 RT (%REF)',
        'cov_isi': '\\u0394 CoV ISI (%)',
    }

    for tracking in ['Trapezoid', 'Pyramid']:
        subset = df_mu[df_mu['tracking_type'] == tracking]
        if subset.empty:
            continue

        fig, axes = plt.subplots(1, len(key_metrics), figsize=(4 * len(key_metrics), 5))

        for ax, metric in zip(axes, key_metrics):
            bars_data = []
            bar_labels = []
            bar_colors = []

            for muscle in sorted(subset['muscle'].unique()):
                m_data = subset[subset['muscle'] == muscle]
                pre = m_data[m_data['condition'] == 'Pre_Intervention'][metric].dropna()
                post_con = m_data[m_data['condition'] == 'Post_CON'][metric].dropna()
                post_exz = m_data[m_data['condition'] == 'Post_EXZ'][metric].dropna()

                pre_mean = pre.mean() if len(pre) > 0 else np.nan
                muscle_short = muscle.replace('Right', '').replace('Left', '')

                if len(post_con) > 0 and not np.isnan(pre_mean):
                    delta_con = post_con.mean() - pre_mean
                    bars_data.append(delta_con)
                    bar_labels.append(f'{muscle_short}\\nCON')
                    bar_colors.append('#2563eb')

                if len(post_exz) > 0 and not np.isnan(pre_mean):
                    delta_exz = post_exz.mean() - pre_mean
                    bars_data.append(delta_exz)
                    bar_labels.append(f'{muscle_short}\\nEXZ')
                    bar_colors.append('#dc2626')

            if bars_data:
                x = np.arange(len(bars_data))
                ax.bar(x, bars_data, color=bar_colors, alpha=0.7, edgecolor='black', linewidth=0.5)
                ax.set_xticks(x)
                ax.set_xticklabels(bar_labels, fontsize=8)
                ax.axhline(0, color='black', linewidth=0.8, linestyle='-')
                ax.set_ylabel(metric_labels[metric], fontsize=10)
                ax.grid(axis='y', alpha=0.3)

        fig.suptitle(f'{tracking} - Change from Pre-Intervention (Post - Pre)',
                     fontsize=13, fontweight='bold', y=1.02)
        plt.tight_layout()
        plt.savefig(WORKFOLDER / f'fig_delta_con_exz_{tracking.lower()}.png', dpi=150, bbox_inches='tight')
        plt.show()
        print(f"Saved: fig_delta_con_exz_{tracking.lower()}.png")'''
    })

    # Section Header - Custom Analysis (Markdown)
    cells.append({
        'cell_type': 'markdown',
        'source': '''## 6. Custom Analysis Section

**Template for your own analysis**

Use this section to add your custom analysis code. Examples:
- Cross-correlations between motor units
- Coherence analysis with reference signal
- Custom recruitment pattern analysis
- Export to custom formats (Excel, MATLAB, etc.)'''
    })

    # Cell 18: Custom Analysis Template (Code)
    cells.append({
        'cell_type': 'code',
        'source': '''# Your custom analysis code here

# Example: Export to Excel
if len(emgfiles) > 0:
    # Create Excel workbook with multiple sheets
    output_excel = WORKFOLDER / "custom_analysis.xlsx"

    # Example: Export discharge times to Excel
    # with pd.ExcelWriter(output_excel, engine='openpyxl') as writer:
    #     for emg_entry in emgfiles:
    #         # Your export logic
    #         pass

    print("Custom analysis placeholder - add your code here")'''
    })

    # Cell 19: Section Header - Export (Markdown)
    cells.append({
        'cell_type': 'markdown',
        'source': '''## 7. Export Results

Save your analysis results to files for publication or further processing.'''
    })

    # Cell 20: Export Results (Code)
    cells.append({
        'cell_type': 'code',
        'source': '''# Export analysis results

# Example exports:
# 1. Motor unit properties DataFrame (already saved above)
# 2. Custom figures
# 3. Summary statistics

print("=" * 60)
print("Export Summary")
print("=" * 60)
print(f"Workfolder: {WORKFOLDER}")
print(f"Files available:")
print(f"  - motor_unit_properties.csv (MU statistics)")
print(f"  - [Add your custom exports here]")
print("\\n✓ Analysis complete!")'''
    })

    return cells
